### ISSUE TITLE
Option to support multiple threads

### ISSUE THREAD

**Issue by Shicheng-Guo** [o1iv3r/ClustImpute#18]
Hi Oliver, 

How about adding a new option to support multiple threads so that the missing value imputation could be much faster? 

Shicheng

**Comment by o1iv3r** [comment]
Hi Shicheng,
I've added some ideas which parts one could parallelize in this item: #7
What's missing and still a todo is an analysis what is the bottleneck to understand which part should be parallelized. Do you have any insights or can share a problem /data set where you experience slow performance? Did you run a profiling?
Best,
Oliver
